repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 src/
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: pytest tests/
        language: system
        pass_filenames: false  # Prevent pytest from trying to test config files