name: CI
#comment added
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint with flake8
        run: flake8 --exit-zero
      - name: Run tests
        run: python -m pytest

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=.
      # Google Chat notification step added below
      - name: Send Google Chat notification
        if: always()  # Send notification whether job succeeds or fails
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          -d '{
            "text": "CI Pipeline Status: ${{ job.status }}\nRepository: ${{ github.repository }}\nEvent: ${{ github.event_name }}\nTriggered by: ${{ github.actor }}\nWorkflow: ${{ github.workflow }}\nCommit: ${{ github.sha }}\nView run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }' \
          "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
